
spring:
  application:
    name: ad-management

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: ${DB_PASSWORD}

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  data:
    web:
      pageable:
        default-page-size: 10

file:
  upload-dir: ./uploads













